---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: Vimmite2
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: stable # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: initramfs
  - type: dnf
    repos:
      copr:
        - atim/starship
        - varlad/zellij
    install:
      packages:
        - zellij
        - starship
        # Core CLI Tools & Shell
        - zsh
        - git
        - neovim
        - bat
        - kitty
        - ncdu
        - fd-find
        - tldr
        - p7zip
        - lsd
        - inxi
        - tmux
        # Multimedia Codecs & Libraries
        - x264
        - x265
        - gstreamer1-plugins-ugly
        - gstreamer1-plugins-bad-freeworld
        # Media Applications
        - vlc
        - mpv
        - yt-dlp
        - mediainfo
        - mixxx
        - flac
        # Container Management
        - podman-compose
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          # Productivity apps
          - org.onlyoffice.desktopeditors
          - md.obsidian.Obsidian
          - org.gimp.GIMP
          - dev.zed.Zed
          - org.telegram.desktop
          - dev.vencord.Vesktop
          - org.signal.Signal
          - re.fossplant.songrec
          # Media applications
          - org.kde.gwenview
          - com.obsproject.Studio
          - org.kde.kdenlive
          - org.blender.Blender
          - org.kde.krita
          - org.jeffvli.feishin
          - net.mediaarea.MediaInfo
          # System utilities
          - com.github.tchx84.Flatseal
          - com.usebottles.bottles
          - net.nokyan.Resources
          - io.github.dimtpap.coppwr
          - com.rustdesk.RustDesk
          - it.mijorus.gearlever
          - com.github.zocker_160.SyncThingy
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
